# Generated by Django 4.0.3 on 2022-03-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_ticket_alter_product_special_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
